server:
  port: 8181

spring:
  main:
    allow-circular-references: true

profiles:
  active: local

application:
  name: lesson 29
  locale: en

  datasource:
    url: &dbUrl jdbc:postgresql://localhost:5432/pgbd
    username: pguser
    password: 123
    driverClassName: org.postgresql.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        default_schema: pgbd@localhost
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    liquibase:
      change-log: 'classpath:db/changelog/db.changelog-master.yaml'